name: Extract VBA Macros

on:
  push:
    paths:
      - '*.xlsm'
  workflow_dispatch:
    inputs:
      github_file_url:
        description: 'URL to the Excel file in GitHub'
        required: true
      output_dir:
        description: 'Path to the output directory'
        required: false
        default: 'default_path_to_output_directory'

jobs:
  extract_vba:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pywin32
          pip install requests

      - name: Run VBA extraction script
        env:
          GITHUB_FILE_URL: ${{ github.event.inputs.github_file_url }}
          OUTPUT_DIR: ${{ github.event.inputs.output_dir }}
        run: |
          python ../extract_vba.py
